### ISSUE TITLE
[BUG] Broken "Can See Box" Implementation

### ISSUE THREAD

**Issue by 1zun4** [CCBlueX/LiquidBounce#6736]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

1.31.1

### Operating System

Linux

### Minecraft Version

1.21.4

### Describe the bug

When standing to close to the target box, the [canSeeBox] implementation will return false, because the check `targetBox.contains(virtualEye)` is not sufficient. Our virtual eye can be outside of the box, but still cause the [PlaneSection] to cast the points incorrectly.

An example can be seen here:

How it's supposed to look like:
<img width="486" height="378" alt="Image" src="https://github.com/user-attachments/assets/89b0a92b-9b42-4852-b12f-0334c1e3e1ee" />

How it looks like when standing too close but far enough to cause [targetBox.contains(virtualEye)] being false:

<img width="1749" height="1324" alt="Image" src="https://github.com/user-attachments/assets/b150e079-5d89-4c7a-93f1-6b769731cd04" />

The issue lies here somewhere: https://github.com/CCBlueX/LiquidBounce/blob/8a0f3bec61548fcdd472a2ed6c03840bdce62d96/src/main/kotlin/net/ccbluex/liquidbounce/utils/aiming/utils/PointFinding.kt#L132-L139

### Steps to reproduce

- Use the following new feature: https://github.com/CCBlueX/LiquidBounce/pull/6735
- Stand too close with an axe to the enemy
- Spam hit because it thinks the target is going out of range

### Client Log

```shell
-
```

**Comment by 1zun4** [comment]
I remember that @ccetl ran into the same issue when he was implementing the CrystalAura as it's used there as well. I have been debugging this issue for the past hour but so far had no luck on understanding the exact reason. I will continue debugging it now, but if that does not help we need to hope for @superblaubeere27 to fix it.

**Comment by sqlerrorthing** [comment]
fixed?

**Comment by 1zun4** [comment]
> fixed?

No? This issue not being closed means it is not fixed.

**Comment by sqlerrorthing** [comment]
i think maybe u forget close this, cuz i saw u merged #6744

**Comment by MukjepScarlet** [comment]
@sqlerrorthing It's still broken. If the enemy is "inside" an incomplete block e.g. glass plane KillAura won't hit anymore.

**Comment by MukjepScarlet** [comment]
Well I think I mentioned one might be another issue. I'm figuring it too.

**Comment by localpthebest** [comment]
what is this even supposed to be

**Comment by MukjepScarlet** [comment]
> If the enemy is "inside" an incomplete block e.g. glass plane KillAura won't hit anymore.

Fixed.

**Comment by MukjepScarlet** [comment]
Currently this bug still exists. At some enclosing position (to enemy), KillAura prefers further target.

**Comment by MukjepScarlet** [comment]
I think it's gone. Can't reproduce now.
